services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: ${ENV}
    ports:
      - "${NEXT_JS_PORT}:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
      - /app/.next
    env_file:
      - .env
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: ${ENV}
    ports:
      - "${NODE_PORT}:5000"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    env_file:
      - .env
  db:
    image: postgres:latest
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db_data:/var/lib/postgresql
    env_file:
      - .env

volumes:
  backend_node_modules:
  frontend_node_modules:
  db_data:
